[package]
name = "minesweeper"
version = "0.1.0"
edition = "2021"
description = "A minesweeper game library"
license = "MIT OR Apache-2.0"

[lib]
name = "minesweeper"
crate-type = ["lib"]

[dependencies]
